version: "3.9"
services:
  pyvis:
    build:
      context: . # ajuste se seus arquivos estão em subpasta
      dockerfile: Dockerfile
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      RPC_NAME: ${RPC_NAME}
      EXPORT_TOKEN: ${EXPORT_TOKEN}
      CORS_ORIGINS: ${CORS_ORIGINS}
    expose:
      - "8000"
    labels:
      - coolify.managed=true
    restart: unless-stopped
