# docker-compose.yml
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  svc-kg:
    build: .
    environment:
      APP_NAME: svc-kg
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      WEB_CONCURRENCY: 2
      CACHE_TTL: 30
      DB_POOL_MAX: 10
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
