version: "3.9"

services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [proxy]

  svc-kg:
    build:
      context: .
      dockerfile: Dockerfile
    image: svc-kg:latest
    environment:
      APP_ENV: production
      PORT: 8080
      WORKERS: 2
      LOG_LEVEL: info

      CORS_ALLOW_ORIGINS: "*"
      CORS_ALLOW_CREDENTIALS: "false"
      CORS_ALLOW_HEADERS: "Authorization,Content-Type"
      CORS_ALLOW_METHODS: "GET,POST,OPTIONS"

      SUPABASE_URL: "https://supabase.mondaha.com"
      SUPABASE_SERVICE_KEY: "<service_role_key>"
      SUPABASE_RPC_FN: "get_graph_membros"
      SUPABASE_TIMEOUT: 15

      CACHE_STATIC_MAX_AGE: 86400
      CACHE_API_TTL: 60

      ENABLE_REDIS_CACHE: "true"
      REDIS_URL: "redis://redis:6379/0"

      # opcional para debug: usar uvicorn em vez de gunicorn
      # SERVER_CMD: uvicorn
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

    # <<< labels Traefik FIXAS (sem ${}) >>>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svckg.rule=Host(`svc-kg.mondaha.com`)"
      - "traefik.http.routers.svckg.entrypoints=websecure"
      - "traefik.http.routers.svckg.tls=true"
      - "traefik.http.services.svckg.loadbalancer.server.port=8080"

    networks: [proxy]

networks:
  proxy:
    external: true
    # MUITO IMPORTANTE: use o NOME EXATO da rede Traefik do seu Coolify
    name: coolify-public
