services:
  pyvis:
    build: .
    container_name: svc-kg
    env_file: [.env]
    expose: ["8000"] # Traefik do Coolify faz o proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped
