openapi: 3.1.0
info:
    title: svc-kg
    version: v1.7.14
    description: |
        Micro serviço de Knowledge Graph (vis.js / PyVis).
        - Suporte a fotos em nós de **membros** via `photo_url` **ou** `foto_path`.
          - `foto_path` absoluto (http/https) é usado diretamente.
          - `foto_path` relativo é servido de **/assets/** (ou **/static/**), e há ícone padrão se ausente.
        - Visualizações: `/v1/vis/visjs`, `/v1/vis/pyvis`
        - Operação: `/live`, `/health`, `/ready`, `/ops/status`
servers:
  - url: /
tags:
  - name: graph
  - name: viz
  - name: ops
paths:
    /v1/graph/membros:
        get:
            tags: [ graph ]
            summary: Retorna grafo (nodes/edges)
            responses: { "200": { description: OK } }
    /v1/vis/visjs:
        get:
            tags: [ viz ]
            summary: Visualização vis-network
            responses: { "200": { description: HTML } }
    /v1/vis/pyvis:
        get:
            tags: [ viz ]
            summary: Visualização PyVis
            responses: { "200": { description: HTML } }
    /live:
        get: { tags: [ ops ], summary: Liveness, responses: { "200": { description: OK } } }
    /health:
        get:
            tags: [ ops ]
            summary: Health check
            parameters:
              - in: query
                name: deep
                schema: { type: boolean, default: false }
            responses: { "200": { description: OK }, "503": { description: Serviço degradado } }
    /ready:
        get: { tags: [ ops ], summary: Readiness, responses: { "200": { description: OK }, "503": { description: Não pronto } } }
    /ops/status:
        get: { tags: [ ops ], summary: Status operacional, responses: { "200": { description: OK } } }
